/* Generated By:JavaCC: Do not edit this line. GramaticaTFGConstants.java */
package parseo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaTFGConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int mapInit = 5;
  /** RegularExpression Id. */
  int nexo = 6;
  /** RegularExpression Id. */
  int vDirUp = 7;
  /** RegularExpression Id. */
  int vDirDown = 8;
  /** RegularExpression Id. */
  int vMov = 9;
  /** RegularExpression Id. */
  int vDesp = 10;
  /** RegularExpression Id. */
  int vIr = 11;
  /** RegularExpression Id. */
  int vZoomOut = 12;
  /** RegularExpression Id. */
  int vZoom = 13;
  /** RegularExpression Id. */
  int vSat = 14;
  /** RegularExpression Id. */
  int vBusca = 15;
  /** RegularExpression Id. */
  int dUp = 16;
  /** RegularExpression Id. */
  int dDown = 17;
  /** RegularExpression Id. */
  int dLeft = 18;
  /** RegularExpression Id. */
  int dRight = 19;
  /** RegularExpression Id. */
  int dSE = 20;
  /** RegularExpression Id. */
  int dSO = 21;
  /** RegularExpression Id. */
  int dNE = 22;
  /** RegularExpression Id. */
  int dNO = 23;
  /** RegularExpression Id. */
  int cuantif = 24;
  /** RegularExpression Id. */
  int Sat = 25;
  /** RegularExpression Id. */
  int zTerm = 26;
  /** RegularExpression Id. */
  int topo = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"mapa\"",
    "<nexo>",
    "<vDirUp>",
    "<vDirDown>",
    "<vMov>",
    "<vDesp>",
    "<vIr>",
    "<vZoomOut>",
    "<vZoom>",
    "<vSat>",
    "<vBusca>",
    "<dUp>",
    "<dDown>",
    "<dLeft>",
    "<dRight>",
    "\"sureste\"",
    "\"suroeste\"",
    "\"noreste\"",
    "\"noroeste\"",
    "<cuantif>",
    "\"satelite\"",
    "\"imagen\"",
    "<topo>",
  };

}
